export const allergies = [
    { value: 'milk', label: 'Milk' },
    { value: 'eggs', label: 'Eggs' },
    { value: 'peanuts', label: 'Peanuts' },
    { value: 'tree_nuts', label: 'Tree nuts (e.g., almonds, walnuts, cashews)' },
    { value: 'soybeans', label: 'Soybeans' },
    { value: 'wheat', label: 'Wheat' },
    { value: 'fish', label: 'Fish' },
    { value: 'shellfish', label: 'Shellfish (e.g., shrimp, crab, lobster)' },
    { value: 'sesame_seeds', label: 'Sesame seeds' },
    { value: 'mustard', label: 'Mustard' },
    { value: 'celery', label: 'Celery' },
    { value: 'lupin', label: 'Lupin' },
    { value: 'sulfites', label: 'Sulfites' },
    { value: 'corn', label: 'Corn' },
    { value: 'red_meat', label: 'Red meat (Alpha-gal allergy)' },
    { value: 'avocado', label: 'Avocado' },
    { value: 'kiwi', label: 'Kiwi' },
    { value: 'banana', label: 'Banana' },
    { value: 'pineapple', label: 'Pineapple' },
    { value: 'mango', label: 'Mango' },
    { value: 'papaya', label: 'Papaya' },
    { value: 'tomato', label: 'Tomato' },
    { value: 'strawberry', label: 'Strawberry' },
    { value: 'peach', label: 'Peach' },
    { value: 'plum', label: 'Plum' },
    { value: 'cherry', label: 'Cherry' },
    { value: 'melons', label: 'Melons (e.g., cantaloupe, honeydew)' },
    { value: 'coconut', label: 'Coconut' },
    { value: 'lentils', label: 'Lentils' },
    { value: 'chickpeas', label: 'Chickpeas' },
    { value: 'buckwheat', label: 'Buckwheat' },
    { value: 'quinoa', label: 'Quinoa' },
    { value: 'rice', label: 'Rice' },
    { value: 'oats', label: 'Oats' },
    { value: 'cinnamon', label: 'Cinnamon' },
    { value: 'nutmeg', label: 'Nutmeg' },
    { value: 'garlic', label: 'Garlic' },
    { value: 'onion', label: 'Onion' },
    { value: 'chives', label: 'Chives' },
    { value: 'fennel', label: 'Fennel' },
    { value: 'radish', label: 'Radish' },
    { value: 'turnip', label: 'Turnip' },
    { value: 'asparagus', label: 'Asparagus' },
    { value: 'mushrooms', label: 'Mushrooms' },
    { value: 'peas', label: 'Peas' },
    { value: 'beets', label: 'Beets' },
    { value: 'cabbage', label: 'Cabbage' },
    { value: 'brussels_sprouts', label: 'Brussels sprouts' },
    { value: 'green_beans', label: 'Green beans' },
    { value: 'lettuce', label: 'Lettuce' }
  ];