name: Deploy Lambda Functions to AWS

on:
  push:
    branches:
      - lambda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Lambda Functions
        run: |
          # Loop through all Python files in your project directory
          for file in $(find ./LambdaFunction/PythonTest -type f -name "*.py"); do
            function_name=$(basename $file .py)
            # Check if the Lambda function exists, if not, create it; otherwise, update it
            if aws lambda get-function-configuration --function-name $function_name 2>/dev/null; then
              aws lambda update-function-code --function-name=$function_name --zip-file fileb://$file
            else
              aws lambda create-function --function-name $function_name \
                --runtime python3.10 \
                --handler lambda_handler \
                --role arn:aws:iam::123456789012:role/lambda-role \
                --code fileb://$file
            fi
          done
