name: Deploy Lambda Functions to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Lambda Functions
        run: |
          # Loop through all Python files in your project directory
          for dir in ./LambdaFunctions/*; do
            if [ -d "$dir" ]; then

              echo "$dir"
              dir_name=$(basename "$dir")

              zip -j $dir_name.zip $dir/*

              echo "Created $dir_name.zip"
              # Check if the Lambda function exists, if not, create it; otherwise, update it
              aws lambda update-function-code --function-name="$dir_name" --zip-file=fileb://$dir_name.zip
              echo "Updated $function_name"
            fi
          done
