name: Deploy

on: 
  push:
    branches:
    - lambda

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          # Setting up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: $ {{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: deploy
        run: |
          zip -j deploy.zip ./LambdaFunctions/PythonTest/*
          aws lambda update-function-code --function-name=lambda-gh-zip-file=fileb://deploy.zip
        